Catch all failures from repomd loads, add warnings, docs
juledwar/soufi pull request #22
Opened 2022-02-25 22:45 UTC by 0xDEC0DE

* There are roughly eleven quintillion failure modes when loading repomd, with zero of them being actionable in any realistic way.  Swallow all failures (not just HTTPErrors) and send back NoneTypes from the subprocess, the callers will similarly roll those over into "no package for you" results.
* Since the YumFinder is designed with the full expectation that a viable, persistent cache is in-place for it to do its work, add an explicit warning if a YumFinder is initialized with the null cache
* Add documentation on how to use caching.
* `launchpadlib` is not thread-safe, and its objects cannot be pickled (https://bugs.launchpad.net/launchpadlib/+bug/822847) which means we cannot use `dogpile.cache` with it, as it assumes both.
* But the call to initialize `launchpadlib` is expensive, so attempt to minimize remote calls within threads, at least.  This will cause duplicated work in concurrent applications, which sadly cannot be avoided.

2022-02-28 01:42 UTC, juledwar requested changes
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/juledwar/soufi/22)* status: 4 of 5 files reviewed, 5 unresolved discussions (waiting on @0xDEC0DE and @juledwar)

___
*[-- commits, line 12 at r1](https://reviewable.io/reviews/juledwar/soufi/22#-Mwxx7HxE02Np9izxCMK):*
I think this is fine, the login is not very intensive, it just adds latency.
___
*[soufi/finders/ubuntu.py, line 33 at r1](https://reviewable.io/reviews/juledwar/soufi/22#-MwxxoPR6ewz9_zeKilH:-MwxxoPR6ewz9_zeKilI:b2yifp) ([raw file](https://github.com/juledwar/soufi/blob/19b9b75d6cff32296fa416327ca6d31a60210e52/soufi/finders/ubuntu.py#L33)):*
> ```Python
>     #  See: https://bugs.launchpad.net/launchpadlib/+bug/822847
>     @classmethod
>     @functools.lru_cache(maxsize=128)
> ```

maxsize can be 1 here, there's only one main archive.
___
*[soufi/finders/yum.py, line 11 at r1](https://reviewable.io/reviews/juledwar/soufi/22#-MwxyTeX6pYReYT5G26J:-MwxyTeX6pYReYT5G26K:ble6438) ([raw file](https://github.com/juledwar/soufi/blob/19b9b75d6cff32296fa416327ca6d31a60210e52/soufi/finders/yum.py#L11)):*
> ```Python
> 
> import repomd
> from dogpile.cache.backends.null import NullBackend as CACHING_DISABLED
> ```

I don't think you need to rename this import, it's perfectly obvious what's going on where it's used in the warning below.
___
*[soufi/finders/yum.py, line 43 at r1](https://reviewable.io/reviews/juledwar/soufi/22#-MwxyhvS4aGNr0wXZnHA:-MwxyhvS4aGNr0wXZnHB:b-tiiz8p) ([raw file](https://github.com/juledwar/soufi/blob/19b9b75d6cff32296fa416327ca6d31a60210e52/soufi/finders/yum.py#L43)):*
> ```Python
>         if isinstance(self._cache.backend, CACHING_DISABLED):
>             warnings.warn(
>                 "disabling caching with the DNF/Yum finder is highly "
> ```

Is it disabled, or just not set? Also, start with a capital letter please.
___
*[soufi/finders/yum.py, line 239 at r1](https://reviewable.io/reviews/juledwar/soufi/22#-MwxyxXQDOIS2hwRF-ZK:-MwxyxXQDOIS2hwRF-ZL:bvcoioa) ([raw file](https://github.com/juledwar/soufi/blob/19b9b75d6cff32296fa416327ca6d31a60210e52/soufi/finders/yum.py#L239)):*
> ```Python
>         #  loading repomd, with zero of them being actionable in any realistic
>         #  way.  Swallow all failures and send back NoneTypes, the callers will
>         #  similarly roll those over into "no package for you" results.
> ```

We should not be swallowing errors, because the finders differentiate between "not found" and "failure". If there's a failure, it needs to bubble up and back to the other side of this pipe.


<!-- Sent from Reviewable.io -->

2022-02-28 01:43 UTC, juledwar commented
I'm using Reviewable for this, BTW. It's quite nice.

2022-02-28 05:45 UTC, juledwar requested changes
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/juledwar/soufi/22)* status: all files reviewed, 5 unresolved discussions (waiting on @0xDEC0DE)



<!-- Sent from Reviewable.io -->

2022-02-28 18:48 UTC, 0xDEC0DE reviewed
> *[Reviewable](https://reviewable.io/reviews/juledwar/soufi/22)* status: all files reviewed, 5 unresolved discussions (waiting on @0xDEC0DE and @juledwar)

___
*[soufi/finders/ubuntu.py, line 33 at r1](https://reviewable.io/reviews/juledwar/soufi/22#-MwxxoPR6ewz9_zeKilH:-Mx0ZLegAjTVuE5QbV1P:bor05rq) ([raw file](https://github.com/juledwar/soufi/blob/19b9b75d6cff32296fa416327ca6d31a60210e52/soufi/finders/ubuntu.py#L33)):*
<details><summary><i>Previously, juledwar (Julian Edwards) wrote…</i></summary><blockquote>

maxsize can be 1 here, there's only one main archive.
</blockquote></details>

Having 127 unused slots isn't really going to hurt anything, though.  128 is the default; it's only explicitly set because of a bug in Python 3.6 that made it a required argument
___
*[soufi/finders/yum.py, line 11 at r1](https://reviewable.io/reviews/juledwar/soufi/22#-MwxyTeX6pYReYT5G26J:-Mx0_18J93CUy4Gif0GR:b-9jju) ([raw file](https://github.com/juledwar/soufi/blob/19b9b75d6cff32296fa416327ca6d31a60210e52/soufi/finders/yum.py#L11)):*
<details><summary><i>Previously, juledwar (Julian Edwards) wrote…</i></summary><blockquote>

I don't think you need to rename this import, it's perfectly obvious what's going on where it's used in the warning below.
</blockquote></details>

Fair enough, I was aiming for "absolutely unambiguous" 
___
*[soufi/finders/yum.py, line 43 at r1](https://reviewable.io/reviews/juledwar/soufi/22#-MwxyhvS4aGNr0wXZnHA:-Mx0_JTt055Y3nLmzjJs:b-1bipcg) ([raw file](https://github.com/juledwar/soufi/blob/19b9b75d6cff32296fa416327ca6d31a60210e52/soufi/finders/yum.py#L43)):*
<details><summary><i>Previously, juledwar (Julian Edwards) wrote…</i></summary><blockquote>

Is it disabled, or just not set? Also, start with a capital letter please.
</blockquote></details>

"Not set" and "disabled" are equivalent in this case, but perhaps there's a better way to state this.
___
*[soufi/finders/yum.py, line 239 at r1](https://reviewable.io/reviews/juledwar/soufi/22#-MwxyxXQDOIS2hwRF-ZK:-Mx0_aycDjEA0vH3pYip:b-7mkwc6) ([raw file](https://github.com/juledwar/soufi/blob/19b9b75d6cff32296fa416327ca6d31a60210e52/soufi/finders/yum.py#L239)):*
<details><summary><i>Previously, juledwar (Julian Edwards) wrote…</i></summary><blockquote>

We should not be swallowing errors, because the finders differentiate between "not found" and "failure". If there's a failure, it needs to bubble up and back to the other side of this pipe.
</blockquote></details>

I'm highly skittish about this, because the naive approach to getting a failure back is to throw in a retry loop.  Which, if the failure is because of a "thundering herd" type problem, means you've now just made it worse.  Having an opinion about what to do in the face of these failure modes is the safer bet, to my mind, and libraries are supposed to help people with this kind of thing.


<!-- Sent from Reviewable.io -->

2022-03-02 04:57 UTC, juledwar requested changes
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/juledwar/soufi/22)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @0xDEC0DE and @juledwar)

___
*[soufi/finders/ubuntu.py, line 33 at r1](https://reviewable.io/reviews/juledwar/soufi/22#-MwxxoPR6ewz9_zeKilH:-Mx7uxqWDPxxrPDDq0VV:bf0fthm) ([raw file](https://github.com/juledwar/soufi/blob/19b9b75d6cff32296fa416327ca6d31a60210e52/soufi/finders/ubuntu.py#L33)):*
<details><summary><i>Previously, 0xDEC0DE (Nicolas Simonds) wrote…</i></summary><blockquote>

Having 127 unused slots isn't really going to hurt anything, though.  128 is the default; it's only explicitly set because of a bug in Python 3.6 that made it a required argument
</blockquote></details>

That's fine technically, it just looks weird to a casual reader because there's only one main archive. Is that bug still in 3.7? We don't support 3.6 in this library. If the bug has gone, get rid of the maxsize. If not, add a comment explaining it.
___
*[soufi/finders/yum.py, line 239 at r1](https://reviewable.io/reviews/juledwar/soufi/22#-MwxyxXQDOIS2hwRF-ZK:-Mx7wpIl03NXXji3ce-O:bu60q) ([raw file](https://github.com/juledwar/soufi/blob/19b9b75d6cff32296fa416327ca6d31a60210e52/soufi/finders/yum.py#L239)):*
<details><summary><i>Previously, 0xDEC0DE (Nicolas Simonds) wrote…</i></summary><blockquote>

I'm highly skittish about this, because the naive approach to getting a failure back is to throw in a retry loop.  Which, if the failure is because of a "thundering herd" type problem, means you've now just made it worse.  Having an opinion about what to do in the face of these failure modes is the safer bet, to my mind, and libraries are supposed to help people with this kind of thing.
</blockquote></details>

Fair, but I don't think that logic should be in the library. Maybe we need another DownloadError child Exception along the lines of ServerError to signify that the DownloadError happened because the server itself told us to GTFO rather than some general comms errors. Then it gives the caller the option of just reacting to DownloadError, or can catch specifically ServerError it it wants to back out.


<!-- Sent from Reviewable.io -->

2022-03-02 05:00 UTC, juledwar reviewed
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/juledwar/soufi/22)* status: all files reviewed, 2 unresolved discussions (waiting on @0xDEC0DE)



<!-- Sent from Reviewable.io -->

2022-03-02 16:41 UTC, 0xDEC0DE reviewed
> *[Reviewable](https://reviewable.io/reviews/juledwar/soufi/22)* status: all files reviewed, 2 unresolved discussions (waiting on @juledwar)

___
*[soufi/finders/ubuntu.py, line 33 at r1](https://reviewable.io/reviews/juledwar/soufi/22#-MwxxoPR6ewz9_zeKilH:-MxAR5mQ7qJsniMBRiDM:b-88bvjv) ([raw file](https://github.com/juledwar/soufi/blob/19b9b75d6cff32296fa416327ca6d31a60210e52/soufi/finders/ubuntu.py#L33)):*
<details><summary><i>Previously, juledwar (Julian Edwards) wrote…</i></summary><blockquote>

That's fine technically, it just looks weird to a casual reader because there's only one main archive. Is that bug still in 3.7? We don't support 3.6 in this library. If the bug has gone, get rid of the maxsize. If not, add a comment explaining it.
</blockquote></details>

Fair.
___
*[soufi/finders/yum.py, line 239 at r1](https://reviewable.io/reviews/juledwar/soufi/22#-MwxyxXQDOIS2hwRF-ZK:-MxARAm17RSKXmN7I86i:b-56tf9y) ([raw file](https://github.com/juledwar/soufi/blob/19b9b75d6cff32296fa416327ca6d31a60210e52/soufi/finders/yum.py#L239)):*
<details><summary><i>Previously, juledwar (Julian Edwards) wrote…</i></summary><blockquote>

Fair, but I don't think that logic should be in the library. Maybe we need another DownloadError child Exception along the lines of ServerError to signify that the DownloadError happened because the server itself told us to GTFO rather than some general comms errors. Then it gives the caller the option of just reacting to DownloadError, or can catch specifically ServerError it it wants to back out.
</blockquote></details>

Maybe, but I can't see soufi inspecting the error and raising different exception types being qualitatively better than just handing the exception back to the caller and letting them do it.  


<!-- Sent from Reviewable.io -->

2022-03-02 19:59 UTC, 0xDEC0DE reviewed
Getting `mock`s into subprocesses on platforms that use `spawn` instead of `fork` (namely, mine) appears to be a non-starter, but making a test function that explodes and simply calling it with `do_task` makes for a far simpler test, and actually tests what you're asking for.  So I'll do that, then.

> *[Reviewable](https://reviewable.io/reviews/juledwar/soufi/22#-:-MxAtIbd4LVTZk1D5dDF:bfsopn8)* status: all files reviewed, 2 unresolved discussions (waiting on @juledwar)



<!-- Sent from Reviewable.io -->

2022-03-02 20:05 UTC, 0xDEC0DE reviewed
> *[Reviewable](https://reviewable.io/reviews/juledwar/soufi/22)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @juledwar)

___
*[soufi/finders/ubuntu.py, line 33 at r1](https://reviewable.io/reviews/juledwar/soufi/22#-MwxxoPR6ewz9_zeKilH:-MxBE4y-ElEcbtme-47J:b159syn) ([raw file](https://github.com/juledwar/soufi/blob/19b9b75d6cff32296fa416327ca6d31a60210e52/soufi/finders/ubuntu.py#L33)):*
<details><summary><i>Previously, 0xDEC0DE (Nicolas Simonds) wrote…</i></summary><blockquote>

Fair.
</blockquote></details>

Huh.  I guess it's still a big in Python 3.7:

https://github.com/juledwar/soufi/runs/5397577006?check_suite_focus=true#step:5:37


<!-- Sent from Reviewable.io -->

2022-03-02 23:27 UTC, juledwar reviewed
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/juledwar/soufi/22)* status: all files reviewed, 1 unresolved discussion (waiting on @0xDEC0DE)

___
*[soufi/finders/yum.py, line 239 at r1](https://reviewable.io/reviews/juledwar/soufi/22#-MwxyxXQDOIS2hwRF-ZK:-MxBwXmv2wv3_FpS54sH:b57mas9) ([raw file](https://github.com/juledwar/soufi/blob/19b9b75d6cff32296fa416327ca6d31a60210e52/soufi/finders/yum.py#L239)):*
<details><summary><i>Previously, 0xDEC0DE (Nicolas Simonds) wrote…</i></summary><blockquote>

Maybe, but I can't see soufi inspecting the error and raising different exception types being qualitatively better than just handing the exception back to the caller and letting them do it.  
</blockquote></details>

We're almost on the same page I think. I am not sure the nuance of my suggestion made it through though — it's about giving the caller more information on the type of failure that would allow them to make better/different choices. So we're still handing back the same base exception and the caller can ignore or catch the child one as it sees fit. Does this make sense?


<!-- Sent from Reviewable.io -->

2022-03-03 00:22 UTC, juledwar reviewed
> *[Reviewable](https://reviewable.io/reviews/juledwar/soufi/22)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @juledwar)

___
*[soufi/finders/yum.py, line 239 at r1](https://reviewable.io/reviews/juledwar/soufi/22#-MwxyxXQDOIS2hwRF-ZK:-MxC8uxU3JrmGsCBfpFo:bi4u47h) ([raw file](https://github.com/juledwar/soufi/blob/19b9b75d6cff32296fa416327ca6d31a60210e52/soufi/finders/yum.py#L239)):*
<details><summary><i>Previously, juledwar (Julian Edwards) wrote…</i></summary><blockquote>

We're almost on the same page I think. I am not sure the nuance of my suggestion made it through though — it's about giving the caller more information on the type of failure that would allow them to make better/different choices. So we're still handing back the same base exception and the caller can ignore or catch the child one as it sees fit. Does this make sense?
</blockquote></details>

Ok this is good, but please add docstring help pointing to the __cause__ in case callers need to see the exception. I'm starting to wonder if we need to do this in all places that raise DownloadError now ...


<!-- Sent from Reviewable.io -->

2022-03-03 00:23 UTC, juledwar requested changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/juledwar/soufi/22)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @0xDEC0DE)



<!-- Sent from Reviewable.io -->

2022-03-03 00:58 UTC, juledwar approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/juledwar/soufi/22)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @0xDEC0DE)



<!-- Sent from Reviewable.io -->

2022-03-03 01:26 UTC, merged